### ISSUE TITLE
 Exclude Admins from Inspector/Agent Table

### ISSUE THREAD

**Issue by tonzxz** [Quanby-IT-Solutions/pcic_web_dashboard#15]

**Comment by joemar25** [comment]
- [ ] Do not display admins in the table for inspectors or agents. Admins should be completely **excluded** from this table.
- [ ] Admins should be **managed** in the **user management** section only.

To Do:

- [ ] Update the table filter to ensure **admins are entirely excluded**.
- [ ] Confirm that admins are only visible and manageable in the user management section.
