### ISSUE TITLE
Enforce Numeric Input and Length Limit for Region User Phone Number

### ISSUE THREAD

**Issue by tonzxz** [Quanby-IT-Solutions/pcic_web_dashboard#27]

**Comment by joemar25** [comment]
When adding a new Region User:

- [ ] Ensure the phone number field only accepts numeric input.
- [ ] Limit the phone number to 11 or 12 digits.

**Comment by KUYAKENN** [comment]
![Screenshot (172)](https://github.com/user-attachments/assets/645baeb7-521c-4f13-8cfe-5081fb88ecfe)
