### ISSUE TITLE
Incorrect UI Message During User Editing

### ISSUE THREAD

**Issue by joemar25** [Quanby-IT-Solutions/pcic_web_dashboard#37]
Description:
- When editing a user, the UI incorrectly displays a "fail to create user" message instead of a relevant edit error message.

To Do:

- [x] Update the UI to show an appropriate error message for user editing failures.

![image](https://github.com/user-attachments/assets/8abc0f70-ccb4-42bb-817f-d7ed4fa1b90a)

**Comment by KUYAKENN** [comment]
![Screenshot (169)](https://github.com/user-attachments/assets/a26f783d-64d4-406c-abc7-9cee2e48cb26)
![Uploading Screenshot (167).png…]()
